config/routes.rb
Rails.application.routes.draw do
  resources :loans
  resources :tags
  resources :favourites
  resources :books
  resources :shelves
  resources :publishers
  resources :authors
  devise_for :users
  #get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/about'
  #get 'about' => 'pages#about'
  #resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/favourite.rb
class Favourite < ApplicationRecord
end

app/models/loan.rb
class Loan < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
end

app/models/shelf.rb
class Shelf < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :set_favourite, only: [:show, :edit, :update, :destroy]

  # GET /favourites
  # GET /favourites.json
  def index
    @favourites = Favourite.all
  end

  # GET /favourites/1
  # GET /favourites/1.json
  def show
  end

  # GET /favourites/new
  def new
    @favourite = Favourite.new
  end

  # GET /favourites/1/edit
  def edit
  end

  # POST /favourites
  # POST /favourites.json
  def create
    @favourite = Favourite.new(favourite_params)

    respond_to do |format|
      if @favourite.save
        format.html { redirect_to @favourite, notice: 'Favourite was successfully created.' }
        format.json { render :show, status: :created, location: @favourite }
      else
        format.html { render :new }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favourites/1
  # PATCH/PUT /favourites/1.json
  def update
    respond_to do |format|
      if @favourite.update(favourite_params)
        format.html { redirect_to @favourite, notice: 'Favourite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favourite }
      else
        format.html { render :edit }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1
  # DELETE /favourites/1.json
  def destroy
    @favourite.destroy
    respond_to do |format|
      format.html { redirect_to favourites_url, notice: 'Favourite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = Favourite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favourite_params
      params.require(:favourite).permit(:user_id, :book_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
  def about
  	
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:ntag, :description, :book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/favourites/_form.html.erb
<%= form_with(model: favourite, local: true) do |form| %>
  <% if favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
      <% favourite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :favourite_user_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.number_field :book_id, id: :favourite_book_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favourites</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favourites.each do |favourite| %>
      <tr>
        <td><%= favourite.user_id %></td>
        <td><%= favourite.book_id %></td>
        <td><%= link_to 'Show', favourite %></td>
        <td><%= link_to 'Edit', edit_favourite_path(favourite) %></td>
        <td><%= link_to 'Destroy', favourite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favourite', new_favourite_path %>

app/views/favourites/new.html.erb
<h1>New Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favourite.user_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @favourite.book_id %>
</p>

<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>